# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:02:37+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBasic
from fastapi import Path, Query

from models import LookupsV2PhoneNumber

app = MCPProxy(
    contact={
        'email': 'support@twilio.com',
        'name': 'Twilio Support',
        'url': 'https://support.twilio.com',
    },
    description='This is the public Twilio REST API.',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    termsOfService='https://www.twilio.com/legal/tos',
    title='Twilio - Lookups',
    version='1.42.0',
    servers=[{'url': 'https://lookups.twilio.com'}],
)


@app.get(
    '/v2/PhoneNumbers/{PhoneNumber}',
    tags=['phone_number_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_phone_number(
    phone_number: str = Path(..., alias='PhoneNumber'),
    fields: Optional[str] = Query(None, alias='Fields'),
    country_code: Optional[str] = Query(None, alias='CountryCode'),
    first_name: Optional[str] = Query(None, alias='FirstName'),
    last_name: Optional[str] = Query(None, alias='LastName'),
    address_line1: Optional[str] = Query(None, alias='AddressLine1'),
    address_line2: Optional[str] = Query(None, alias='AddressLine2'),
    city: Optional[str] = Query(None, alias='City'),
    state: Optional[str] = Query(None, alias='State'),
    postal_code: Optional[str] = Query(None, alias='PostalCode'),
    address_country_code: Optional[str] = Query(None, alias='AddressCountryCode'),
    national_id: Optional[str] = Query(None, alias='NationalId'),
    date_of_birth: Optional[str] = Query(None, alias='DateOfBirth'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
