# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:02:37+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import AnyUrl, BaseModel, Field


class PhoneNumberEnumType(Enum):
    landline = 'landline'
    mobile = 'mobile'
    voip = 'voip'


class PhoneNumberEnumValidationError(Enum):
    TOO_SHORT = 'TOO_SHORT'
    TOO_LONG = 'TOO_LONG'
    INVALID_BUT_POSSIBLE = 'INVALID_BUT_POSSIBLE'
    INVALID_COUNTRY_CODE = 'INVALID_COUNTRY_CODE'
    INVALID_LENGTH = 'INVALID_LENGTH'
    NOT_A_NUMBER = 'NOT_A_NUMBER'


class LookupsV2PhoneNumber(BaseModel):
    call_forwarding: Optional[Any] = Field(
        None,
        description='An object that contains information on the unconditional call forwarding status of mobile phone number.',
    )
    caller_name: Optional[Any] = Field(
        None,
        description='An object that contains caller name information based on [CNAM](https://support.twilio.com/hc/en-us/articles/360051670533-Getting-Started-with-CNAM-Caller-ID).',
    )
    calling_country_code: Optional[str] = Field(
        None,
        description='International dialing prefix of the phone number defined in the E.164 standard.',
    )
    country_code: Optional[str] = Field(
        None,
        description="The phone number's [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).",
    )
    identity_match: Optional[Any] = Field(
        None,
        description='An object that contains identity match information. The result of comparing user-provided information including name, address, date of birth, national ID, against authoritative phone-based data sources',
    )
    line_type_intelligence: Optional[Any] = Field(
        None,
        description='An object that contains line type information including the carrier name, mobile country code, and mobile network code.',
    )
    live_activity: Optional[Any] = Field(
        None,
        description='An object that contains live activity information for a mobile phone number.',
    )
    national_format: Optional[str] = Field(
        None,
        description='The phone number in [national format](https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers).',
    )
    phone_number: Optional[str] = Field(
        None,
        description='The phone number in [E.164](https://www.twilio.com/docs/glossary/what-e164) format, which consists of a + followed by the country code and subscriber number.',
    )
    sim_swap: Optional[Any] = Field(
        None,
        description='An object that contains information on the last date the subscriber identity module (SIM) was changed for a mobile phone number.',
    )
    sms_pumping_risk: Optional[Any] = Field(
        None,
        description='An object that contains information on if a phone number has been currently or previously blocked by Verify Fraud Guard for receiving malicious SMS pumping traffic as well as other signals associated with risky carriers and low conversion rates.',
    )
    url: Optional[AnyUrl] = Field(None, description='The absolute URL of the resource.')
    valid: Optional[bool] = Field(
        None,
        description='Boolean which indicates if the phone number is in a valid range that can be freely assigned by a carrier to a user.',
    )
    validation_errors: Optional[List[PhoneNumberEnumValidationError]] = Field(
        None,
        description='Contains reasons why a phone number is invalid. Possible values: TOO_SHORT, TOO_LONG, INVALID_BUT_POSSIBLE, INVALID_COUNTRY_CODE, INVALID_LENGTH, NOT_A_NUMBER.',
    )
